import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, Check, LoaderCircle, Play, ShieldCheck } from "lucide-react";
import { api } from "./api";
import type { Decision, EventRecord, Experiment, Research } from "./types";

export type CanvasView="SETUP"|"HYPOTHESIS"|"PLAN"|"RUN"|"ANALYZE"|"COMPARE"|"DECIDE"|"REPORT"|"TIMELINE";
const fmt=(value:unknown,digits=3)=>typeof value==="number"&&Number.isFinite(value)?value.toFixed(digits):"—";
const sourceClass=(value?:string)=>`source-badge source-${(value||"SYSTEM").toLowerCase().replaceAll("_","-")}`;

function Topology({density}:{density?:unknown[]}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!ref.current||!Array.isArray(density)||!density.length)return;let grid=density as number[][];if(Array.isArray(grid[0]?.[0])){const volume=density as unknown as number[][][];grid=volume.map(row=>row.map(column=>Math.max(...column)))}const h=grid.length,w=grid[0]?.length||0;if(!w)return;const canvas=ref.current,ctx=canvas.getContext("2d")!;canvas.width=Math.max(480,w*6);canvas.height=Math.max(260,h*6);ctx.fillStyle="#f6f7f8";ctx.fillRect(0,0,canvas.width,canvas.height);grid.forEach((row,y)=>row.forEach((raw,x)=>{const value=Math.max(0,Math.min(1,Number(raw))),shade=Math.round(247-value*220);ctx.fillStyle=`rgb(${shade},${shade+Math.round(value*8)},${shade+Math.round(value*14)})`;ctx.fillRect(x*canvas.width/w,y*canvas.height/h,Math.ceil(canvas.width/w),Math.ceil(canvas.height/h))}))},[density]);return <canvas className="topology-canvas" ref={ref}/>}
function Curve({history}:{history?:Array<Record<string,number>>}){const values=(history||[]).map(i=>Number(i.compliance)).filter(Number.isFinite);if(!values.length)return <div className="empty-mini">—</div>;const min=Math.min(...values),max=Math.max(...values),span=Math.max(1e-9,max-min),points=values.map((v,i)=>`${i/Math.max(1,values.length-1)*500},${120-(v-min)/span*100}`).join(" ");return <svg className="convergence" viewBox="0 0 500 130" preserveAspectRatio="none"><polyline points={points}/></svg>}

type Props={research:Research;selected?:Experiment;streamText:string;view:CanvasView;setView:(v:CanvasView)=>void;onSelect:(id:string)=>void;onAutonomous:()=>void;onDecision:(d:Decision,a:"approve"|"reject"|"why")=>void;onEdit:(d:Decision)=>void};
export default function ExperimentCanvas({research,selected,streamText,view,setView,onSelect,onAutonomous,onDecision,onEdit}:Props){
  const zh=research.locale==="zh-CN",l=(cn:string,en:string)=>zh?cn:en,pending=research.decisions.filter(d=>d.status==="PENDING"),running=research.experiments.find(e=>e.status==="RUNNING")||selected;
  const [compareIds,setCompareIds]=useState<[string,string]>([research.experiments[0]?.id||"",research.experiments[1]?.id||research.experiments[0]?.id||""]),[comparison,setComparison]=useState<Record<string,any>|null>(null);
  useEffect(()=>{if(view==="COMPARE"&&compareIds[0]&&compareIds[1]&&compareIds[0]!==compareIds[1])api.researchCompare(research.id,...compareIds).then(setComparison).catch(()=>setComparison(null))},[view,compareIds,research.id]);
  const latestAgent=useMemo(()=>[...research.events].reverse().find(e=>e.source==="PI_AGENT"&&e.type==="AGENT_MESSAGE"),[research.events]);
  const tabs:CanvasView[]=["SETUP","HYPOTHESIS","PLAN","RUN","ANALYZE","COMPARE","DECIDE","REPORT","TIMELINE"];
  return <div className="canvas-shell"><div className="canvas-tabs">{tabs.map(item=><button className={view===item?"active":""} key={item} onClick={()=>setView(item)}>{item}</button>)}<button className="canvas-run" onClick={onAutonomous}><Play/> {l("启动闭环","Start loop")}</button></div><div className="canvas-body">
    {view==="SETUP"&&<><div className="canvas-kicker">IMMUTABLE RESEARCH CONTRACT</div><div className="canvas-heading"><div><h2>{research.name}</h2><p>{research.goal}</p></div><span className="source-badge source-human">CONFIRMED</span></div><section className="canvas-panel"><h3>{l("契约事实","Contract facts")}</h3><pre>{JSON.stringify(research.contract||{geometry:research.geometry,material:research.material,loads:research.loads,boundary_conditions:research.boundary_conditions,constraints:research.constraints,budgets:research.budgets},null,2)}</pre></section><p className="setup-note">{l("目标、工程边界和已完成实验不会被 Agent 静默修改。","The Agent cannot silently change goals, engineering boundaries, or completed experiments.")}</p></>}
    {view==="HYPOTHESIS"&&<><div className="canvas-kicker">HYPOTHESIZE · MULTI-ROLE REVIEW</div><div className="canvas-heading"><h2>{l("假设与竞争解释","Hypotheses & competing explanations")}</h2></div>{(research.hypotheses||[]).length===0?<div className="empty-state"><SparkIcon/><h2>{l("尚无正式假设","No formal hypothesis yet")}</h2><p>{l("启动闭环后，Hypothesis Subagent 将依据事实与知识条目提出可检验假设。","The Hypothesis Subagent will create testable hypotheses from facts and cited knowledge.")}</p></div>:(research.hypotheses||[]).map(item=><section className="canvas-panel" key={item.id}><div className="canvas-kicker">ROUND {item.round_number} · {item.status}</div><h3>{item.statement}</h3>{item.competing?.length?<ul>{item.competing.map(value=><li key={value}>{value}</li>)}</ul>:null}<small>Evidence: {(item.evidence_ids||[]).join(", ")||"—"}</small></section>)}<section className="canvas-panel"><h3>{l("Subagent 审查轨迹","Subagent review trail")}</h3>{(research.subagent_tasks||[]).map(task=><div className="decision-actions" key={task.id}><b>{task.role}</b><span>{task.objective}</span><span className={`status status-${task.status.toLowerCase()}`}>{task.status}</span></div>)}</section></>}
    {view==="PLAN"&&<><div className="canvas-kicker">ROUND {Math.max(1,(research.current_round||0)+1)} · PLAN</div><div className="canvas-heading"><div><h2>{l("科研计划","Research plan")}</h2><p>{research.goal}</p></div><span className={sourceClass(pending[0]?.source||"PI_AGENT")}>{pending[0]?.source||"PI_AGENT / POLICY"}</span></div><section className="canvas-panel"><h3>Research Contract</h3><div className="contract-grid"><div><span>{l("几何","Geometry")}</span><b>{String(research.geometry?.type||"—")}</b></div><div><span>{l("模式","Mode")}</span><b>{research.mode}</b></div><div><span>{l("体积分数","Volume")}</span><b>{fmt(research.constraints.volume_fraction)}</b></div><div><span>{l("灰度约束","Gray limit")}</span><b>{fmt(research.constraints.gray_max)}</b></div><div><span>{l("连通性","Connectivity")}</span><b>{research.constraints.connected?"REQUIRED":"OPTIONAL"}</b></div><div><span>{l("预算","Budget")}</span><b>{research.budget_used}/{research.budget_total}</b></div></div></section><section className="canvas-panel"><h3>{l("当前证据与意图","Current evidence & intent")}</h3><p>{latestAgent?.body||l("启动闭环后，Pi 将先读取 Research Context 与预算，再选择科学意图。","Pi will read authoritative context and budget before selecting a scientific intent.")}</p>{pending.map(d=><div key={d.id} className="decision-actions"><b>{d.proposal.fidelity}</b><span>{d.reason}</span><button className="approve" onClick={()=>onDecision(d,"approve")}>{l("批准","Approve")}</button><button onClick={()=>onEdit(d)}>{l("编辑","Edit")}</button><button onClick={()=>onDecision(d,"reject")}>{l("拒绝","Reject")}</button><button onClick={()=>onDecision(d,"why")}>Why</button></div>)}</section></>}
    {view==="RUN"&&<RunView experiment={running} zh={zh}/>} 
    {view==="ANALYZE"&&<AnalyzeView experiment={selected} agent={latestAgent} streamText={streamText} zh={zh}/>} 
    {view==="DECIDE"&&<DecideView decisions={pending} research={research} onDecision={onDecision} onEdit={onEdit} zh={zh}/>} 
    {view==="REPORT"&&<><div className="canvas-kicker">FACT-GROUNDED REPORT</div><div className="canvas-heading"><div><h2>{l("研究报告与复现证据","Research report & reproducibility")}</h2><p>{l("报告只读取 Research State；缺失值写“未计算”。","Reports only read Research State; unavailable values are marked as not calculated.")}</p></div><span className="source-badge source-evaluator">DETERMINISTIC</span></div><section className="canvas-panel report-actions"><h3>Markdown / PDF</h3><button className="approve" onClick={()=>api.downloadReport(research.id,"markdown")}>Markdown</button><button onClick={()=>api.downloadReport(research.id,"pdf")}>PDF</button></section><section className="canvas-panel"><h3>Artifact Lineage</h3>{(research.artifact_lineage||[]).length?(research.artifact_lineage||[]).map(item=><div className="decision-actions" key={item.id}><b>{item.artifact_type}</b><span>{item.sha256||"—"}</span><small>{item.path||"—"}</small></div>):<p>—</p>}</section></>}
    {view==="COMPARE"&&<><div className="canvas-kicker">DETERMINISTIC COMPARE</div><div className="canvas-heading"><h2>{l("实验对比","Experiment comparison")}</h2></div><div className="compare-selectors">{[0,1].map(index=><select key={index} value={compareIds[index]} onChange={e=>setCompareIds(current=>index===0?[e.target.value,current[1]]:[current[0],e.target.value])}>{research.experiments.map(exp=><option key={exp.id}>{exp.id}</option>)}</select>)}</div><div className="compare-grid">{compareIds.map(id=>{const exp=research.experiments.find(e=>e.id===id);return <section className="canvas-panel" key={id}><h3>{id} · {exp?.fidelity}</h3><div className="canvas-topology"><Topology density={exp?.result?.artifacts?.density}/></div><div className="evaluator-verdict"><div><span>Compliance</span><b>{fmt(exp?.result?.objective?.compliance)}</b></div><div><span>Gray</span><b>{fmt(exp?.result?.quality?.gray_ratio)}</b></div><div><span>Components</span><b>{exp?.result?.quality?.connected_components??"—"}</b></div><div><span>Source</span><b>{exp?.result_source||"—"}</b></div></div></section>})}</div>{comparison&&<section className="canvas-panel"><h3>Evaluator Difference</h3><pre>{JSON.stringify(comparison,null,2)}</pre></section>}</>}
    {view==="TIMELINE"&&<><div className="canvas-kicker">AUDIT TIMELINE</div><div className="canvas-heading"><h2>{l("研究事件","Research events")}</h2></div><div className="timeline-list">{research.events.map(event=><button className="timeline-event" key={event.event_id||event.id} onClick={()=>event.experiment_id&&onSelect(event.experiment_id)}><span className={sourceClass(event.source)}>{event.source||"SYSTEM"}</span><div><header><b>{event.type||event.kind}</b><small>{new Date(event.created_at).toLocaleTimeString()}</small></header><h4>{event.title}</h4><p>{event.body}</p></div></button>)}</div></>}
  </div></div>;
}

function SparkIcon(){return <span style={{fontSize:36,color:"#9b7ee5"}}>◇</span>}

function RunView({experiment,zh}:{experiment?:Experiment;zh:boolean}){const l=(cn:string,en:string)=>zh?cn:en;if(!experiment)return <div className="empty-state"><Activity/><h2>{l("当前没有运行实验","No experiment is running")}</h2></div>;return <><div className="canvas-kicker">{experiment.id} · RUN · {experiment.result_source||"LIVE_REAL_RUN"}</div><div className="canvas-heading"><div><h2>{experiment.purpose}</h2><p>{experiment.fidelity} · {experiment.backend}</p></div><span className="status status-running">{experiment.status} {Math.round((experiment.progress||0)*100)}%</span></div><div className="run-layout"><section className="canvas-panel"><h3>Topology</h3><div className="canvas-topology"><Topology density={experiment.result?.artifacts?.density}/></div></section><div className="canvas-metrics"><div className="canvas-metric"><span>Compliance</span><b>{fmt(experiment.result?.objective?.compliance)}</b></div><div className="canvas-metric"><span>Gray ratio</span><b>{fmt(experiment.result?.quality?.gray_ratio)}</b></div><div className="canvas-metric"><span>Connected</span><b>{experiment.result?.quality?.connected_components===1?"PASS":experiment.result?"FAIL":"—"}</b></div><div className="canvas-metric"><span>Iteration</span><b>{experiment.current_iteration}</b></div></div></div><section className="canvas-panel"><h3>Convergence</h3><Curve history={experiment.result?.artifacts?.history}/></section></>}
function AnalyzeView({experiment,agent,streamText,zh}:{experiment?:Experiment;agent?:EventRecord;streamText:string;zh:boolean}){const l=(cn:string,en:string)=>zh?cn:en;if(!experiment?.result)return <div className="empty-state"><ShieldCheck/><h2>{l("选择一个已完成实验","Select a completed experiment")}</h2></div>;const result=experiment.result,evaluation=result.evaluation||{};return <><div className="canvas-kicker">{experiment.id} · ANALYZE</div><div className="canvas-heading"><div><h2>{evaluation.success?"FEASIBLE":"INFEASIBLE / PARTIAL"}</h2><p>{l("事实 → 确定性评价 → Pi 解释","Facts → deterministic verdict → Pi interpretation")}</p></div><span className="source-badge source-evaluator">EVALUATOR</span></div><section className="canvas-panel"><h3>Raw FEM Facts</h3><div className="evaluator-verdict"><div><span>Compliance</span><b>{fmt(result.objective?.compliance)}</b></div><div><span>Gray</span><b>{fmt(result.quality?.gray_ratio)}</b></div><div><span>Volume</span><b>{fmt(result.constraints?.volume_fraction)}</b></div><div><span>Components</span><b>{result.quality?.connected_components??"—"}</b></div></div></section><section className="canvas-panel"><h3>Evaluator Verdict</h3><pre>{JSON.stringify(evaluation,null,2)}</pre></section><section className="canvas-panel"><h3>Pi Interpretation</h3><span className="source-badge source-pi-agent">PI_AGENT</span><p>{streamText||agent?.body||l("尚无 Pi 解释。确定性证据仍然有效。","No Pi interpretation yet. Deterministic evidence remains valid.")}</p></section></>}
function DecideView({decisions,research,onDecision,onEdit,zh}:{decisions:Decision[];research:Research;onDecision:Props["onDecision"];onEdit:Props["onEdit"];zh:boolean}){const l=(cn:string,en:string)=>zh?cn:en;if(!decisions.length)return <div className="empty-state"><Check/><h2>{l("没有待审批决策","No pending decisions")}</h2></div>;return <>{decisions.map(d=>{const humanRequired=String(d.proposal.fidelity||"").startsWith("F3");return <section key={d.id} className="canvas-panel"><div className="canvas-kicker">{d.id} · {d.source||"PI_AGENT"}</div><div className="canvas-heading"><div><h2>{d.proposal.fidelity}</h2><p>{d.reason}</p></div><span className={`status status-${d.risk.toLowerCase()}`}>{d.risk}</span></div><div className="decision-chain"><div className="decision-node"><span>PI_AGENT</span><b>{d.source||"PI_AGENT"}</b></div><div className="decision-node"><span>POLICY_ENGINE</span><b>{JSON.stringify(d.proposal.parameters)}</b></div><div className="decision-node"><span>SAFETY_GUARD</span><b>PASS</b></div><div className="decision-node"><span>BUDGET</span><b>{research.budget_total-research.budget_used} LEFT</b></div><div className="decision-node"><span>HUMAN_GATE</span><b>{humanRequired?"REQUIRED":"AUTO"}</b></div><div className="decision-node"><span>EXECUTOR</span><b>WAITING</b></div></div><div className="decision-actions"><button className="approve" onClick={()=>onDecision(d,"approve")}>{l("批准运行","Approve")}</button><button onClick={()=>onEdit(d)}>{l("编辑并复检","Edit & recheck")}</button><button onClick={()=>onDecision(d,"reject")}>{l("拒绝","Reject")}</button><button onClick={()=>onDecision(d,"why")}>Why</button></div></section>})}</>}
