"""Generate deterministic TypeScript mirrors of Python API/tool contracts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from topoptpilot.schemas.api_contracts import (
    ApiError,
    EventEnvelope,
    ExecutionSpec,
    PromotionRequest,
    PromotionResult,
    SourceSnapshot,
    StreamTicket,
)
from topoptpilot.tools.contracts import TOOL_CONTRACTS


def _json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True)


def outputs() -> dict[Path, str]:
    schemas = {
        model.__name__: model.model_json_schema(by_alias=True)
        for model in (
            ApiError, EventEnvelope, ExecutionSpec, PromotionRequest,
            PromotionResult, SourceSnapshot, StreamTicket,
        )
    }
    api = (
        "// Generated by scripts/generate_contracts.py; do not edit.\n"
        f"export const API_SCHEMAS = {_json(schemas)} as const;\n"
        "export interface ApiError { code: string; message: string; source: \"API\" | \"POLICY\" | \"MATLAB\" | \"RUNTIME\" | \"AGENT\" | \"EVALUATOR\"; retryable: boolean; detail: Record<string, unknown> }\n"
        "export interface StreamTicket { ticket: string; expiresIn: number }\n"
        "export interface ArtifactRef { relativePath: string; sha256: string; mediaType: string; sizeBytes: number }\n"
        "export interface EventEnvelope { eventId: string; type: string; source: string; timestamp: string; ownerType: \"engineering_run\" | \"research\" | \"experiment\"; ownerId: string; runId?: string | null; experimentId?: string | null; payload: Record<string, unknown> }\n"
        "export interface SourceSnapshot { snapshotId: string; sourceDigest: string; configDigest: string; environment: Record<string, unknown>; sourceFiles: ArtifactRef[]; artifacts: ArtifactRef[]; provenance: Record<string, unknown>; originRunId: string; createdAt: string }\n"
        "export interface PromotionRequest { name: string; goal: string; budgetTotal: number }\n"
        "export interface PromotionResult<TResearch = Record<string, unknown>> { researchId: string; snapshot: SourceSnapshot; research: TResearch }\n"
        "export type FinalReviewVerdict = \"APPROVE\" | \"REVISE\" | \"REJECT\";\n"
        "export type QuickRunStatus = \"queued\" | \"running\" | \"completed\" | \"failed\" | \"cancelled\";\n"
    )
    tools = (
        "// Generated by scripts/generate_contracts.py; do not edit.\n"
        f"export const TOOL_CONTRACTS = {_json(TOOL_CONTRACTS)} as const;\n"
        "export const TOOL_NAMES = new Set(Object.keys(TOOL_CONTRACTS));\n"
    )
    return {
        ROOT / "desktop/src/generated/api-contract.ts": api,
        ROOT / ".pi/generated/topopt-tools.ts": tools,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        raise SystemExit("Generated contracts are stale: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
